spring.application.name=password-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/passwordmanager
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
telegram.bot.token=8669896566:AAFWRO-nrAoXOAX4lImE9QM7hjRsstdJiO4
telegram.bot.username=@dreampear
